<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="0" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-17T15:43:44 EDT" name="Suite" finished-at="2023-07-17T15:44:27 EDT" duration-ms="43075">
    <groups>
    </groups>
    <test started-at="2023-07-17T15:43:44 EDT" name="Test" finished-at="2023-07-17T15:44:27 EDT" duration-ms="43075">
      <class name="com.naveenAutomation.FrameworkDemo.YourStoreTest">
        <test-method is-config="true" signature="setUpLogger()[pri:0, instance:com.naveenAutomation.FrameworkDemo.YourStoreTest@3c73951]" started-at="2023-07-17T15:43:44 EDT" name="setUpLogger" finished-at="2023-07-17T15:43:44 EDT" duration-ms="119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpLogger -->
        <test-method is-config="true" signature="setUP()[pri:0, instance:com.naveenAutomation.FrameworkDemo.YourStoreTest@3c73951]" started-at="2023-07-17T15:43:44 EDT" name="setUP" finished-at="2023-07-17T15:43:51 EDT" duration-ms="6683" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method signature="ValidateLogin()[pri:0, instance:com.naveenAutomation.FrameworkDemo.YourStoreTest@3c73951]" started-at="2023-07-17T15:43:51 EDT" name="ValidateLogin" finished-at="2023-07-17T15:43:51 EDT" duration-ms="768" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateLogin -->
      </class> <!-- com.naveenAutomation.FrameworkDemo.YourStoreTest -->
      <class name="com.naveenAutomation.FrameworkDemo.AccountLoginTest">
        <test-method is-config="true" signature="setUpLogger()[pri:0, instance:com.naveenAutomation.FrameworkDemo.AccountLoginTest@3d5c822d]" started-at="2023-07-17T15:43:51 EDT" name="setUpLogger" finished-at="2023-07-17T15:43:51 EDT" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpLogger -->
        <test-method is-config="true" signature="setUP()[pri:0, instance:com.naveenAutomation.FrameworkDemo.AccountLoginTest@3d5c822d]" started-at="2023-07-17T15:43:51 EDT" name="setUP" finished-at="2023-07-17T15:43:57 EDT" duration-ms="5271" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method retried="true" signature="testfailure()[pri:0, instance:com.naveenAutomation.FrameworkDemo.AccountLoginTest@3d5c822d]" started-at="2023-07-17T15:43:57 EDT" name="testfailure" finished-at="2023-07-17T15:43:57 EDT" duration-ms="13" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [JudeT] but found [Jude]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [JudeT] but found [Jude]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.naveenAutomation.FrameworkDemo.AccountLoginTest.testfailure(AccountLoginTest.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testfailure -->
        <test-method is-config="true" signature="setUP()[pri:0, instance:com.naveenAutomation.FrameworkDemo.AccountLoginTest@3d5c822d]" started-at="2023-07-17T15:43:57 EDT" name="setUP" finished-at="2023-07-17T15:44:02 EDT" duration-ms="5791" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method retried="true" signature="testfailure()[pri:0, instance:com.naveenAutomation.FrameworkDemo.AccountLoginTest@3d5c822d]" started-at="2023-07-17T15:44:02 EDT" name="testfailure" finished-at="2023-07-17T15:44:02 EDT" duration-ms="5" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [JudeT] but found [Jude]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [JudeT] but found [Jude]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.naveenAutomation.FrameworkDemo.AccountLoginTest.testfailure(AccountLoginTest.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testfailure -->
        <test-method is-config="true" signature="setUP()[pri:0, instance:com.naveenAutomation.FrameworkDemo.AccountLoginTest@3d5c822d]" started-at="2023-07-17T15:44:02 EDT" name="setUP" finished-at="2023-07-17T15:44:08 EDT" duration-ms="5905" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method signature="testfailure()[pri:0, instance:com.naveenAutomation.FrameworkDemo.AccountLoginTest@3d5c822d]" started-at="2023-07-17T15:44:08 EDT" name="testfailure" finished-at="2023-07-17T15:44:08 EDT" duration-ms="5" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [JudeT] but found [Jude]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [JudeT] but found [Jude]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.naveenAutomation.FrameworkDemo.AccountLoginTest.testfailure(AccountLoginTest.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testfailure -->
        <test-method is-config="true" signature="setUP()[pri:0, instance:com.naveenAutomation.FrameworkDemo.AccountLoginTest@3d5c822d]" started-at="2023-07-17T15:44:09 EDT" name="setUP" finished-at="2023-07-17T15:44:15 EDT" duration-ms="6337" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method signature="validateLoginUsingInvalidVredentials()[pri:0, instance:com.naveenAutomation.FrameworkDemo.AccountLoginTest@3d5c822d]" started-at="2023-07-17T15:44:15 EDT" name="validateLoginUsingInvalidVredentials" finished-at="2023-07-17T15:44:18 EDT" duration-ms="2436" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginUsingInvalidVredentials -->
        <test-method is-config="true" signature="setUP()[pri:0, instance:com.naveenAutomation.FrameworkDemo.AccountLoginTest@3d5c822d]" started-at="2023-07-17T15:44:18 EDT" name="setUP" finished-at="2023-07-17T15:44:24 EDT" duration-ms="5820" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method signature="validateLoginUsingValidCredentials()[pri:0, instance:com.naveenAutomation.FrameworkDemo.AccountLoginTest@3d5c822d]" started-at="2023-07-17T15:44:24 EDT" name="validateLoginUsingValidCredentials" finished-at="2023-07-17T15:44:27 EDT" duration-ms="3086" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLoginUsingValidCredentials -->
      </class> <!-- com.naveenAutomation.FrameworkDemo.AccountLoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
